version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create cloudformation stack
          command:
            aws cloudformation deploy --template-file template.yml --stack-name mystack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0c:27:6e:9b:82:4b:03:e9:38:80:bf:0d:ac:6f:11:b1"
      - run:
          name: install ansible
          command: apk add --update ansible
      - run:
          name: run playbook and configure server
          command: ansible-playbook -i inventory main2.yml
          


workflows:
  mywrokflow1:
    jobs:
      #- create_infrastructure
      - configure_infrastructure